# Generated by Django 4.2 on 2023-05-09 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='fw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.user', verbose_name='팔로워'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='fl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='users.user', verbose_name='팔로우'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('fw', 'fl')},
        ),
    ]
