# Generated by Django 4.2 on 2023-05-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='생일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='프로필 사진'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscript',
            field=models.TextField(blank=True, null=True, verbose_name='자기소개'),
        ),
    ]
