# Generated by Django 4.2 on 2023-05-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, null=True, verbose_name='나이'),
        ),
    ]
